import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Bot, CalendarCheck, Cloud, GraduationCap, MessageSquareText, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteLayout } from "@/components/study-sync/site-shell";
import { DashboardMockup } from "@/components/study-sync/dashboard-mockup";
import { DeviceShowcase } from "@/components/study-sync/device-showcase";
import { FeatureCard, SectionHeading } from "@/components/study-sync/page";

export const Route = createFileRoute("/")({
  head: () => ({meta:[
    {title:"Study Sync — The Smart Academic Companion"},{name:"description",content:"Organize lectures, simplify learning with AI, connect families and stay in sync across every device."},{property:"og:title",content:"Study Sync — The Smart Academic Companion"},{property:"og:description",content:"Smarter learning for students, parents and teachers."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}
  ],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"SoftwareApplication",name:"Study Sync",applicationCategory:"EducationalApplication",operatingSystem:"macOS, Android, iOS, Windows",description:"A connected academic companion for students, parents and teachers."})}]}),
  component: Index,
});

// IMPORTANT: Replace this placeholder. See ./README.md for routing conventions.
function Index() {
  return <SiteLayout>
    <section className="relative overflow-hidden px-5 pb-24 pt-36 sm:px-8 lg:px-12 lg:pt-44"><div className="pointer-events-none absolute left-1/2 top-20 h-80 w-2/3 -translate-x-1/2 rounded-full bg-accent/10 blur-3xl"/><div className="relative mx-auto max-w-7xl text-center"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/8 px-3 py-1.5 text-xs text-primary"><Sparkles className="size-3"/>Built for how learning happens now</div><h1 className="text-shine mx-auto max-w-5xl text-5xl font-semibold leading-[1.02] sm:text-7xl lg:text-8xl">The Smart Academic Companion for Students, Parents and Teachers</h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Track lectures, simplify learning with AI, connect families and stay organized across every device.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Button size="lg" asChild><Link to="/downloads">Download for macOS <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><Link to="/downloads">Android — Coming Soon</Link></Button><Button size="lg" variant="ghost" asChild><Link to="/downloads">iPhone — Coming Soon</Link></Button></div><DashboardMockup/></div></section>
    <section className="border-y border-border px-5 py-20 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="One academic workspace" title="Everyone sees what matters to them." copy="One connected system turns daily learning into clear, useful context for students, families and educators." align="center"/><div className="mt-12 grid gap-4 md:grid-cols-3"><FeatureCard icon={GraduationCap} title="For students" copy="Capture lectures, organize notes, plan assignments and build a learning rhythm that lasts."/><FeatureCard icon={UsersRound} title="For parents" copy="Understand progress through calm summaries and jargon-free explanations, without hovering."/><FeatureCard icon={ShieldCheck} title="For teachers" copy="Maintain lecture records, assignments and class-level insights from one focused workspace."/></div></div></section>
    <section className="px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Study Sync AI" title="Turn every lecture into momentum." copy="A context-aware assistant summarizes what happened, extracts homework and explains difficult ideas at the right level."/><div className="mt-12 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="glass-panel rounded-lg p-6 sm:p-8"><div className="mb-6 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary"><Bot/></span><div><p className="font-semibold">Study Sync AI</p><p className="text-xs text-muted-foreground">Physics · Lecture 08</p></div></div><div className="ml-auto max-w-md rounded-lg bg-secondary p-4 text-sm">Can you explain wave-particle duality like I’m preparing for tomorrow’s quiz?</div><div className="mt-4 max-w-lg rounded-lg border border-primary/20 bg-primary/5 p-5 text-sm leading-6 text-muted-foreground"><p className="font-medium text-foreground">Think of light as a flexible performer.</p><p className="mt-2">When it travels and interferes, it behaves like a wave. When we measure it, it arrives in individual packets called photons.</p><div className="mt-4 border-t border-border pt-4 text-xs text-primary">Key takeaway: the experiment determines which behavior becomes visible.</div></div></div><div className="grid gap-4"><FeatureCard icon={MessageSquareText} title="Parent-friendly explanations" copy="Translate complex course content into clear context families can understand."/><FeatureCard icon={CalendarCheck} title="Homework extraction" copy="Turn lecture notes into dated, prioritized assignments automatically."/></div></div></div></section>
    <section className="border-y border-border px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Every screen, one rhythm" title="Designed to move with your day." copy="Start on a Mac, check the plan on your phone, and review progress from any screen." align="center"/><DeviceShowcase/><div className="mt-8 flex flex-wrap justify-center gap-8 text-sm text-muted-foreground"><span>macOS available</span><span>Android in development</span><span>iPhone in development</span><span>Windows planned</span></div></div></section>
    <section className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Trusted by focused learners" title="Less chasing. More understanding." align="center"/><div className="mt-12 grid gap-4 md:grid-cols-3">{[["Study Sync turns a full day of classes into a plan I can actually follow.","Maya, Student"],["I understand what my son is learning without asking for every detail.","Daniel, Parent"],["My lecture records and assignments finally live in the same place.","Amelia, Teacher"]].map(([q,n])=><blockquote key={n} className="glass-soft rounded-lg p-6"><p className="leading-7">“{q}”</p><footer className="mt-6 text-xs text-primary">{n}</footer></blockquote>)}</div></div></section>
    <section className="px-5 pb-24 sm:px-8"><div className="glass-panel mx-auto max-w-5xl rounded-lg p-8 text-center sm:p-12"><Cloud className="mx-auto size-8 text-primary"/><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Your learning, finally in sync.</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">Start with the macOS app today. Your connected academic workspace is ready.</p><Button size="lg" className="mt-7" asChild><Link to="/downloads">Explore downloads <ArrowRight/></Link></Button></div></section>
  </SiteLayout>;
}
